from __future__ import annotations
from typing import List, Dict, Any, Literal
from server.agents.base_agent import BaseAgent
from pydantic import BaseModel, Field
import json
from pathlib import Path


class RiskCounts(BaseModel):
    high: int = Field(0, description="Count of high risk issues")
    medium: int = Field(0, description="Count of medium risk issues")
    ok: int = Field(0, description="Count of clauses that are ok")


class FlaggedClause(BaseModel):
    id: str = Field(..., description="Unique identifier for the clause")
    category: Literal[
        "Unfair Clauses", "Your Rights", "Stamp Duty", "Legal Issues", "Financial Terms"
    ] = Field(..., description="Category of the issue")
    risk: Literal["HIGH", "MEDIUM", "OK"] = Field(
        ..., description="Risk level of the issue"
    )
    title: str = Field(..., description="Short title describing the issue")
    description: str = Field(..., description="Detailed description of the issue")
    anchor: str = Field(..., description="Reference to the clause location")


class Artifact(BaseModel):
    id: str = Field(..., description="Unique identifier for the artifact")
    name: str = Field(..., description="Display name of the artifact")
    type: Literal["ics", "email", "rider", "pdf"] = Field(
        ..., description="Type of artifact"
    )
    url: str = Field(..., description="URL to download the artifact")


class DashboardData(BaseModel):
    riskCounts: RiskCounts = Field(..., description="Summary of risk counts")
    flaggedClauses: List[FlaggedClause] = Field(
        [], description="List of flagged clauses with issues"
    )
    artifacts: List[Artifact] = Field(
        [], description="List of generated artifacts for download"
    )


class PackagerV2Agent(BaseAgent):
    """
    Packages analysis results into a format expected by the frontend dashboard.
    """

    def __init__(self):
        super().__init__()
        self.output_dir = Path("server/agents/outputs")
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.output_file = self.output_dir / "dashboard_data.json"

    def package_results(
        self,
        analysis_result: Dict[str, Any],
        planner_email_output=None,
        ics_file_path=None,
    ) -> DashboardData:
        """
        Transform analysis results into the format expected by the frontend.

        Args:
            analysis_result: The analysis results from the AnalyserAgent
            planner_email_output: Optional output from PlannerAgent's email generation
            ics_file_path: Optional path to ICS file generated by PlannerAgent
        """
        # Extract risk counts from the summary
        summary = analysis_result.get("summary", {})
        risk_counts = RiskCounts(
            high=summary.get("high_risk", 0),
            medium=summary.get("medium_risk", 0),
            ok=summary.get("ok", 0),
        )

        # Transform issues into flagged clauses
        issues = analysis_result.get("issues", [])
        flagged_clauses = []

        for i, issue in enumerate(issues):
            if issue.get("risk") in [
                "HIGH",
                "MEDIUM",
            ]:  # Only include HIGH and MEDIUM risks
                clause_id = str(i + 1)
                anchor = f"clause-{clause_id}"

                flagged_clauses.append(
                    FlaggedClause(
                        id=clause_id,
                        category=self._map_category(issue.get("category", "")),
                        risk=issue.get("risk", "MEDIUM"),
                        title=issue.get("clause", "")[
                            :50
                        ],  # Use first 50 chars as title
                        description=issue.get("rationale", ""),
                        anchor=anchor,
                    )
                )

        # Create artifacts with real paths from planner agent outputs
        artifacts = []

        # Add ICS file artifact if provided or exists
        if ics_file_path and Path(ics_file_path).exists():
            ics_path = Path(ics_file_path)
            artifacts.append(
                Artifact(
                    id="calendar",
                    name="Meeting Schedule",
                    type="ics",
                    url=f"/download/{ics_path.name}",
                )
            )
        else:
            # Fall back to default location
            ics_path = self.output_dir / "planner_event.ics"
            if ics_path.exists():
                artifacts.append(
                    Artifact(
                        id="calendar",
                        name="Meeting Schedule",
                        type="ics",
                        url=f"/download/{ics_path.name}",
                    )
                )

        # Add email draft artifact if exists or provided
        if planner_email_output:
            # If email output is directly provided, we'll save it first
            with open(
                self.output_dir / "planner-agent.json", "w", encoding="utf-8"
            ) as f:
                if isinstance(planner_email_output, dict):
                    json.dump(planner_email_output, f, ensure_ascii=False, indent=2)
                else:
                    # Handle if it's a Pydantic model with dict() method
                    json.dump(
                        planner_email_output.dict(), f, ensure_ascii=False, indent=2
                    )

            artifacts.append(
                Artifact(
                    id="email",
                    name="Legal Recommendations Email",
                    type="email",
                    url="/download/planner-agent.json",
                )
            )
        else:
            # Fall back to checking if the file exists
            email_path = self.output_dir / "planner-agent.json"
            if email_path.exists():
                artifacts.append(
                    Artifact(
                        id="email",
                        name="Legal Recommendations Email",
                        type="email",
                        url=f"/download/{email_path.name}",
                    )
                )

        # Keep other artifacts as needed - could be generated in the future
        artifacts.append(
            Artifact(
                id="pdf",
                name="Annotated Agreement",
                type="pdf",
                url="/download/annotated-agreement",
            )
        )

        # Create the complete dashboard data
        dashboard_data = DashboardData(
            riskCounts=risk_counts, flaggedClauses=flagged_clauses, artifacts=artifacts
        )

        # Save to file for persistence
        with open(self.output_file, "w", encoding="utf-8") as f:
            json.dump(dashboard_data.model_dump(), f, ensure_ascii=False, indent=2)

        return dashboard_data

    def _map_category(self, category: str) -> str:
        """Map analysis categories to frontend categories."""
        category_map = {
            "unfair": "Unfair Clauses",
            "rights": "Your Rights",
            "stamp duty": "Stamp Duty",
            "legal": "Legal Issues",
            "financial": "Financial Terms",
        }

        for key, value in category_map.items():
            if key.lower() in category.lower():
                return value

        # Default category if no match
        return "Legal Issues"
