on:
  push:
    branches:
      - main

jobs:
  eslint:
    name: Eslint
    runs-on: ubuntu-latest
    steps:
      - name: check out environment
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: npm install
        run: npm ci
        working-directory: client
    
      - name: eslint
        uses: icrawl/action-eslint@v1
        with:
          custom-glob: client


